[package]
name = "zktrie_rust"
authors = ["xgao@zoyoe.com"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "zktrie_rust"
path = "src/lib.rs"

[dependencies]
strum = "0.24.1"
strum_macros = "0.24.1"
ff = "0.12"
rand = "0.8"
ark-std = { version = "0.3.0", features = ["print-trace"] }
serde = { version = "1.0", features = ["serde_derive"] }
serde_json = "1.0"
clap = { version = "3.2.22", features = ["derive", "cargo"] }
subtle = "2.4"
lazy_static = "1.4.0"
hex = "0.4"
lru = "0.11.0"
num-integer = "0.1"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2.15"
num-derive = "0.3"
num = "0.4"

